name: CI

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:
#     inputs:
#       java:
#         type: boolean
#         description: JAVA
#       dotnet:
#         type: boolean
#         description: DOTNET
#       python:
#         type: boolean
#         description: PYTHON
#       ruby:
#         type: boolean
#         description: RUBY
#       php:
#         type: boolean
#         description: PHP
#       ts:
#         type: boolean
#         description: TS
#       go:
#         type: boolean
#         description: GO
#       swift:
#         type: boolean
#         description: SWIFT
on:
  workflow_dispatch:
    inputs:
      Version:
        description: "This input field requires version in [format](https://www.google.com): x.y.z, where x => major version, y => minor version and z => patch version"
        required: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: |
          echo "boolean is ${{ github.event.inputs.java }}" / ${{ inputs.java }}
          echo "boolean is ${{ github.event.inputs.dotnet }}" / ${{ inputs.dotnet }}
          echo "boolean is ${{ github.event.inputs.python }}" / ${{ inputs.python }}
          echo "boolean is ${{ github.event.inputs.ruby }}" / ${{ inputs.ruby }}
          echo "boolean is ${{ github.event.inputs.php }}" / ${{ inputs.php }}
          echo "boolean is ${{ github.event.inputs.ts }}" / ${{ inputs.ts }}
          echo "boolean is ${{ github.event.inputs.go }}" / ${{ inputs.go }}
          echo "boolean is ${{ github.event.inputs.swift }}" / ${{ inputs.swift }}
          
